### ISSUE TITLE
attempt to call field 'nvim_add_user_command' (a nil value)

### ISSUE THREAD

**Issue by mrlay** [elianiva/asciidoclive.nvim#1]
### nvim --version
- NVIM v0.10.0-dev-bb38c06
- Build type: RelWithDebInfo
- LuaJIT 2.1.1693350652

### OS: mac

does api 'nvim_add_user_command' not support in  v0.10.0-dev ?

**Comment by elianiva** [comment]
I'm sorry but this repository should've been archived since I don't really use Neovim anymore.
